local_costmap:
  global_frame: map
  robot_base_frame: $(arg base_frame)
  update_frequency: 5.0
  publish_frequency: 5.0
  # static_map: false
  rolling_window: true
  width: 11
  height: 11
  resolution: 0.1
  transform_tolerance: 0.5
  track_unknown_space: true
  plugins:
   - {name: static_layer,        type: "costmap_2d::StaticLayer"}
   - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
   - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
