costmap_common_params.yaml:

  # Robot footprint
  #footprint: [[-0.3, -0.3], [-0.3, 0.3], [0.3, 0.3], [0.3, -0.3]]
  footprint_padding: 0.01

  # Obstacle and inflation layers
  obstacle_layer:
    enabled: true
    obstacle_range: 2.5
    raytrace_range: 3.0
    max_obstacle_height: 0.6
    min_obstacle_height: 0.0
    combination_method: 1

  inflation_layer:
    enabled: true
    inflation_radius: 0.3
    cost_scaling_factor: 5.0

  # Update and publish frequency
  update_frequency: 5.0
  publish_frequency: 2.0

  # Resolution and origin
  resolution: 0.05
  origin_x: 0.0
  origin_y: 0.0

  # Sensor information
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: $(arg laser_frame), data_type: LaserScan, topic: $(arg scan), marking: true, clearing: true}


