DWAPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 5
  min_vel_x: -0.5

  max_vel_y: 0
  min_vel_y: 0

# The velocity when robot is moving in a straight line
  max_vel_trans:  0.1
  min_vel_trans:  0.05

  max_vel_theta: 2.75
  min_vel_theta: 1.37

  acc_lim_x: 0.5
  acc_lim_y: 0.0
  acc_lim_theta: 3.2 

# Goal Tolerance Parametes
  xy_goal_tolerance: 0.4
  yaw_goal_tolerance: 0.7
  latch_xy_goal_tolerance: true

# Forward Simulation Parameters
  sim_time: 20
  vx_samples: 5
  vy_samples: 0
  vth_samples: 10
  controller_frequency: 5.0

# Trajectory Scoring Parameters
  path_distance_bias: 8.0
  goal_distance_bias: 20.0
  occdist_scale: 0.1
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

# Oscillation Prevention Parameters
  oscillation_reset_dist: 20
  oscillation_reset_angle: 25

# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true